seed: 42
exp_name: ddpg_epoch_1200_obs_type_0
policy: ddpg
timeout_steps: 80
data_dir: carla_cost_20
episode_rerun_num: 100
sample_episode_num: 20
evaluate_episode_num: 10
pretrain_dir: planning/data_all/ddpg_epoch_1200_obs_type_0/ddpg_epoch_1200_obs_type_0_s42/
continue_from_epoch: 0
obs_type: 0
ddpg:
    num_qc: 1
    cost_limit: 20
    use_cost_decay: false
    cost_start: 100
    cost_end: 5
    decay_epoch: 200
    KP: 0.1
    KI: 0.003
    KD: 0.001
    steps_per_epoch: 2000
    actor_lr: 0.0003
    critic_lr: 0.001
    ac_model: mlp
    hidden_sizes:
    - 256
    - 256
    act_noise: 0.1
    gamma: 0.99
    polyak: 0.995
    num_q: 1
    worker_config:
        save_trajectories: 0
        warmup_steps: 600
        batch_size: 100
        buffer_size: 20000
