type_dir: 'safebench/scenario/config/scenario_type'
type_name: 'advtraj.json'
type_category: 'planning'

route_dir: 'safebench/scenario/scenario_data/route'
method: null
scenario_id: null
route_id: null

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 3.0

model_path: 'safebench/scenario/scenario_data/model_ckpt/advtraj'
save_freq: 80
