policy_type: 'scenic'
scenario_category: 'scenic'

route_dir: 'safebench/scenario/scenario_data/route'
scenic_dir: 'safebench/scenario/scenario_data/scenic_data/scenario_3'
sample_num: 50
opt_step: 10
select_num: 2

method: 'scenic'
scenario_id: 3
route_id: [0,1,2,3,4,5,6,7,8,9]

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 3.0

# not useful
model_path: ''
standard_action: False
buffer_capacity: 100
eval_in_train_freq: 10
save_freq: 10
train_episode: 100
